linters:
  disable:
    - gci
    - funlen
    - testpackage
    - exhaustruct
    - exhaustivestruct
    - tagliatelle

  enable-all: true
  # enable:
  #   - asasalint
  #   - asciicheck
  #   - bidichk
  #   - bodyclose
  #   - containedctx
  #   - contextcheck
  #   - cyclop
  #   - deadcode
  #   - decorder
  #   - depguard
  #   - dogsled
  #   - dupl
  #   - dupword
  #   - durationcheck
  #   - errcheck
  #   - errchkjson
  #   - errname
  #   - errorlint
  #   - execinquery
  #   - exhaustive
  #   - exhaustivestruct
  #   - exhaustruct
  #   - exportloopref
  #   - forbidigo
  #   - forcetypeassert
  #   - funlen
  #   - gci
  #   - ginkgolinter
  #   - gochecknoglobals
  #   - gochecknoinits
  #   - gocognit
  #   - goconst
  #   - gocritic
  #   - gocyclo
  #   - godot
  #   - godox
  #   - goerr113
  #   - gofmt
  #   - gofumpt
  #   - goheader
  #   - goimports
  #   - golint
  #   - gomnd
  #   - gomoddirectives
  #   - gomodguard
  #   - goprintffuncname
  #   - gosec
  #   - gosimple
  #   - govet
  #   - grouper
  #   - ifshort
  #   - importas
  #   - ineffassign
  #   - interfacebloat
  #   - interfacer
  #   - ireturn
  #   - lll
  #   - loggercheck
  #   - maintidx
  #   - makezero
  #   - maligned
  #   - misspell
  #   - nakedret
  #   - nestif
  #   - nilerr
  #   - nilnil
  #   - nlreturn
  #   - noctx
  #   - nolintlint
  #   - nonamedreturns
  #   - nosnakecase
  #   - nosprintfhostport
  #   - paralleltest
  #   - prealloc
  #   - predeclared
  #   - promlinter
  #   - reassign
  #   - revive
  #   - rowserrcheck
  #   - scopelint
  #   - sqlclosecheck
  #   - staticcheck
  #   - structcheck
  #   - stylecheck
  #   - tagliatelle
  #   - tenv
  #   - testableexamples
  #   - testpackage
  #   - thelper
  #   - tparallel
  #   - typecheck
  #   - unconvert
  #   - unparam
  #   - unused
  #   - usestdlibvars
  #   - varcheck
  #   - varnamelen
  #   - wastedassign
  #   - whitespace
  #   - wrapcheck
  #   - wsl

  # Enable presets.
  # https://golangci-lint.run/usage/linters
  # presets:
  #   - bugs
  #   - comment
  #   - complexity
  #   - error
  #   - format
  #   - import
  #   - metalinter
  #   - module
  #   - performance
  #   - sql
  #   - style
  #   - test
  #   - unused
